openapi: 3.0.3

info:
    title: BackOffice SUAP to Ente Terzo SUAP

    version: 1.0.0

    description: |- 
      API rese disponibili da BackOffice SUAP a Ente Terzo SUAP'

    contact:
        name: AgID - Agenzia per l'Italia Digitale
        url:  https://www.agid.gov.it/

    license:
        name: CC BY-NC-SA 4.0
        url:  https://creativecommons.org/licenses/by-nc-sa/4.0/

servers:
    -
        url: xxxxxxxx
        description: Generated server url
        
paths:
    
    /send_conclusions:
        post:
            requestBody:
                content:
                    application/json:
                      schema:
                         $ref: '#/components/schemas/SendConclusionRequests'
                required: true
            responses:
                "200": 
                    description: 'Ack'                         
            security:
                - bearerAuth: []
                  Agid-JWS-Signature: [] 

    /request_cdss:
        post:
            requestBody:
                content:
                    application/json:
                      schema:
                         $ref: https://raw.githubusercontent.com/AgID/suap-gt-specifiche/to_interoperabilita-protocols/to_interoperabilita/schema/cui-schema.yaml
                required: true
            responses:
                "200": 
                    description: 'Ack'                         
            security:
                - bearerAuth: []
                  Agid-JWS-Signature: [] 

    /request_integration:
        post:
            requestBody:
                content:
                    application/json:
                      schema:
                         $ref: '#/components/schemas/RequestIntegrationRequest'
                required: true
            responses:
                "200": 
                    description: 'Ack'                         
            security:
                - bearerAuth: []
                  Agid-JWS-Signature: [] 


    /instance/{cui_uuid}/document/{resource_id}/{access_token}:
        get:
            parameters:
                -   name: cui_uuid
                    in: path
                    description: UUID del CUI
                    required: true
                    schema:
                        type: string
                -   name: resource_id
                    in: path
                    description: id risorsa  procedimento
                    required: true
                    schema:
                        type: string
                -   name: access_token
                    in: path
                    description: token per l'accesso alla risorsa 
                    required: true
                    schema:
                        type: string

               
            responses:
                "200": 
                    description: 'TODO: return result XML,PDF, or Binary'
                    content:
                        text/plain:
                            schema:
                                type: string
                                format: byte
             
            security:
                - bearerAuth: []
                  Agid-JWS-Signature: []                
    
     

components:
  schemas:    
        RequestIntegrationRequest:
          type: object
          properties:
            cui:
                $ref: https://raw.githubusercontent.com/AgID/suap-gt-specifiche/to_interoperabilita-protocols/to_interoperabilita/schema/cui-schema.yaml
            integration_list:
                type: array
                items:
                    type: object
                    required:
                    - code
                    - ref
                    - integration_request
                    properties:
                        code:
                            title: codice della fattispecie presente nel Catalogo
                            type: string
                            minLength: 1
                        ref:
                            title: riferimento all'elemento dell'istanza relativo al procedimento
                            type: string
                            minLength: 1
                        integration_request:       
                            title: integrazione richiesta
                            type: string
                        resource_id:
                            title: id della risorsa "documento di richiesta integrazione", univoco per erogatore e CUI.UUID
                            type: string
                            minLength: 1
                        access_token:
                            title: token per l'accesso alla risorsa
                            type: string
                            minLength: 1
                                
            resource_id:
                title: id della risorsa, univoco per erogatore e CUI.UUID
                type: string
                minLength: 1
            access_token:
                title: token per l'accesso alla risorsa
                type: string
                minLength: 1           

        SendConclusionRequests:
            type: object
            oneOf:
              - $ref: '#/components/schemas/SuspendRequired'
              - $ref: '#/components/schemas/ConformationRequired'
              - $ref: '#/components/schemas/PositiveOutcome'
        
        SuspendRequired: 
            type: object
            required:
              - cui
              - suspend_motivation
            properties:
                cui:
                    $ref: 'https://raw.githubusercontent.com/AgID/suap-gt-specifiche/to_interoperabilita-protocols/to_interoperabilita/schema/cui-schema.yaml'
                suspend_motivation:
                    type: string
                    minLength: 1
                resource_id:
                    title: id della risorsa "documento di richiesta sospensione", univoco per erogatore e CUI.UUID
                    type: string
                    minLength: 1
                access_token:
                    title: token per l'accesso alla risorsa
                    type: string
                    minLength: 1

        ConformationRequired:
            type: object
            required:
                - cui
                - date
                - conformation_requested
            properties:
                cui:
                    $ref: 'https://raw.githubusercontent.com/AgID/suap-gt-specifiche/to_interoperabilita-protocols/to_interoperabilita/schema/cui-schema.yaml'
                date: 
                    type: string
                    format: date
                conformation_requested:
                    type: string
                    minLength: 1
                resource_id:
                    title: id della risorsa "documento di richiesta conformazione", univoco per erogatore e CUI.UUID
                    type: string
                    minLength: 1
                access_token:
                    title: token per l'accesso alla risorsa
                    type: string
                    minLength: 1
                

        PositiveOutcome:
            required:
              - cui
              - outcome
            properties:
                cui:
                    $ref: 'https://raw.githubusercontent.com/AgID/suap-gt-specifiche/to_interoperabilita-protocols/to_interoperabilita/schema/cui-schema.yaml'
                positive_outcome:
                    type: string
                    minLength: 1
                resource_id:
                    title: id della risorsa "documento di parere positivo", univoco per erogatore e CUI.UUID
                    type: string
                    minLength: 1
                access_token:
                    title: token per l'accesso alla risorsa 
                    type: string
                    minLength: 1
    
        

  headers:
      Agid-JWS-Signature:
          schema:
              format: JWS
              maxLength: 4096
              type: string
              example: eyJzd.fafa.fafafa
          description: |-
              L'header Agid-JWS-Signature è un JWS (JSON Web Signature) che contiene una firma digitale
              associata al messaggio scambiato.
              Vedi il pattern di sicurezza [INTEGRITY_REST_01] del MoDI
              
  securitySchemes:
      bearerAuth:
          scheme: bearer
          bearerFormat: JWT
          type: http
          description: Implementazione conforme ad RFC8725
          
      Agid-JWS-Signature:
          type: apiKey
          description: |-
              Header della firma di JWS.
              Il valore di questo header è una firma JWS.
              Vedere Modi  [integrity_rest_01] Integrità del payload del messaggio REST
          name: Agid-JWS-Signature
          in: header
