openapi: 3.0.3

info:
    title: FrontOffice SUAP to BackOffice SUAP

    version: 1.0.0

    description: |- 
      API rese disponibili da FrontOffice SUAP a BackOffice SUAP'

    contact:
        name: AgID - Agenzia per l'Italia Digitale
        url:  https://www.agid.gov.it/

    license:
        name: CC BY-NC-SA 4.0
        url:  https://creativecommons.org/licenses/by-nc-sa/4.0/

servers:
    -
        url: xxxxxxxx
        description: Generated server url
        
paths:
    
    
   
    /request_correction:
        post:
            requestBody:
                content:
                    application/json:
                      schema:
                         $ref: '#/components/schemas/RequestCorrectionRequest'
                required: true
            responses:
                "200": 
                    description: 'Ack'                         
            security:
                - bearerAuth: []
                  Agid-JWS-Signature: [] 

    /request_integration:
        post:
            requestBody:
                content:
                    application/json:
                      schema:
                         $ref: '#/components/schemas/RequestIntegrationRequest'
                required: true
            responses:
                "200": 
                    description: 'Ack'                         
            security:
                - bearerAuth: []
                  Agid-JWS-Signature: [] 

    /instance/{cui_uuid}/document/{resource_id}/{access_token}:
        get:
            parameters:
                -   name: cui_uuid
                    in: path
                    description: UUID del CUI
                    required: true
                    schema:
                        type: string
                -   name: resource_id
                    in: path
                    description: id risorsa  procedimento
                    required: true
                    schema:
                        type: string
                -   name: token
                    in: path
                    description: token per l'accesso alla risorsa 
                    required: true
                    schema:
                        type: string

               
            responses:
                "200": 
                    description: Restituisce la parte dell'istanza richiesta, codificata in base64, il mime type relativo è specificato nel descrittore dell'istanza
                    content:
                        text/plain:
                            schema:
                                type: string
                                format: byte
                           
    
      
            security:
                - bearerAuth: []
                  Agid-JWS-Signature: []                
    
     
    /notify:
        post:
          requestBody:
                content:
                    application/json: 
                      schema:
                        $ref: '#/components/schemas/NotifyMessage'
                required: true
          responses:
                "200": 
                    description: 'ack'

          security:
            - bearerAuth: []
              Agid-JWS-Signature: []     

components:
  schemas:   
        RequestCorrectionRequest:
          type: object
          properties:
            cui:
                $ref: https://raw.githubusercontent.com/AgID/suap-gt-specifiche/to_interoperabilita-protocols/to_interoperabilita/schema/cui-schema.yaml
            correction_list:
                type: array
                items:
                    type: object
                    required:
                    - code
                    - ref
                    - correction_requested
                    properties:
                        code:
                            title: codice della fattispecie presente nel Catalogo
                            type: string
                            minLength: 1
                        ref:
                            title: riferimento all'elemento dell'istanza relativo al procedimento
                            type: string
                            minLength: 1
                        correction_request:       
                            title: testo correzione richiesta
                            type: string
                  
                         

        RequestIntegrationRequest:
          type: object
          properties:
            cui:
                $ref: https://raw.githubusercontent.com/AgID/suap-gt-specifiche/to_interoperabilita-protocols/to_interoperabilita/schema/cui-schema.yaml
            integration_list:
                type: array
                items:
                    type: object
                    required:
                    - code
                    - ref
                    - integration_requested
                    properties:
                        code:
                            title: codice della fattispecie presente nel Catalogo
                            type: string
                            minLength: 1
                        ref:
                            title: riferimento all'elemento dell'istanza relativo al procedimento (procedimento o allegato)
                            type: string
                            minLength: 1
                        integration_request:       
                            title: elenco integrazioni richieste da uno o più enti terzi
                            type: array
                            items:
                                type: object
                                properties:
                                    request:
                                        title: testo integrazione richiesta
                                        type: string
                                    requester_administration:
                                        title: amministrazione richiedente
                                        $ref: "https://raw.githubusercontent.com/AgID/suap-gt-specifiche/to_interoperabilita-protocols/to_interoperabilita/schema/administration-schema.yaml" 
            
            integration_document_list:
                type: array
                items: 
                    type: object
                    properties:
                        requester_administration:
                            title: amministrazione richiedente
                            $ref: "https://raw.githubusercontent.com/AgID/suap-gt-specifiche/to_interoperabilita-protocols/to_interoperabilita/schema/administration-schema.yaml" 
                        resource_id:
                            title: id della risorsa "documento di richiesta integrazioni", univoco per erogatore e CUI.UUID
                            type: string
                            minLength: 1
                        access_token:
                            title: token per l'accesso alla risorsa
                            type: string
                            minLength: 1

        
        NotifyMessage:
            type: object
            required:
                - cui
                - event
                
            properties:
                cui:
                    $ref: 'https://raw.githubusercontent.com/AgID/suap-gt-specifiche/to_interoperabilita-protocols/to_interoperabilita/schema/cui-schema.yaml'   

                event:
                    type: string
                    enum:
                    - end_by_instance_refused
                    - end_by_proceeding_time_expired
                    - end_by_suspend_required
                    - end_by_conformation_required
                    - end_by_positive_outcome
                    - end_by_integration_times_expired
                    - cdss_convened
                
                resource_id:
                            title: se presente, id della risorsa documento correlata all'evento notificato (es. nel caso di "end_by_positive_outcome", id risorsa "documento di parere positivo", univoco per erogatore e CUI.UUID
                            type: string
                            minLength: 1
                access_token:
                    title: token per l'accesso alla risorsa
                    type: string
                    minLength: 1


  headers:
      Agid-JWS-Signature:
          schema:
              format: JWS
              maxLength: 4096
              type: string
              example: eyJzd.fafa.fafafa
          description: |-
              L'header Agid-JWS-Signature è un JWS (JSON Web Signature) che contiene una firma digitale
              associata al messaggio scambiato.
              Vedi il pattern di sicurezza [INTEGRITY_REST_01] del MoDI
              
  securitySchemes:
      bearerAuth:
          scheme: bearer
          bearerFormat: JWT
          type: http
          description: Implementazione conforme ad RFC8725
          
      Agid-JWS-Signature:
          type: apiKey
          description: |-
              Header della firma di JWS.
              Il valore di questo header è una firma JWS.
              Vedere Modi  [integrity_rest_01] Integrità del payload del messaggio REST
          name: Agid-JWS-Signature
          in: header
