openapi: 3.0.3

info:
    title: ComUnica to FrontOffice SUAP

    version: 1.0.0

    description: |-
        API rese disponibili da ComUnica a FrontOffice SUAP

    contact:
        name: AgID - Agenzia per l'Italia Digitale
        url: https://www.agid.gov.it/

    license:
        name: CC BY-NC-SA 4.0
        url: https://creativecommons.org/licenses/by-nc-sa/4.0/

servers:
    - url: https://<system host+subdomains>.it
      description: ComUnica to FrontOffice SUAP endpoint

paths:
    /retry:
        post:
            description: Richiesta di ritrasmissione dati relativi ad una specifica operation a causa di incoerenze riscontrate sui dati ricevuti.
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                cui:
                                    $ref: https://raw.githubusercontent.com/AgID/suap-gt-specifiche/to_interoperabilita-protocols/to_interoperabilita/schema/cui-schema.yaml
                                operation:
                                    description: operation per la quale si richiede la ritrasmissione
                                    type: string
                                    enum:
                                        - notify
                                error:
                                    $ref: "#/components/schemas/Error"

            responses:
                "200":
                    $ref: "#/components/responses/OKRequest"
                "400":
                    $ref: "#/components/responses/BadRequest"
                "401":
                    $ref: "#/components/responses/Unauthorized"
                "500":
                    $ref: "#/components/responses/ServerError"
                "503":
                    $ref: "#/components/responses/ServiceUnavaliable"

            security:
                - bearerAuth: []
                  Agid-JWS-Signature: []

    /send_instance:
        description: Invio riferimenti istanza
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/SendInstanceRequest"
                required: true
            responses:
                "200":
                    $ref: "#/components/responses/OKRequest"
                "400":
                    $ref: "#/components/responses/BadRequest"
                "401":
                    $ref: "#/components/responses/Unauthorized"
                "500":
                    $ref: "#/components/responses/ServerError"
                "503":
                    $ref: "#/components/responses/ServiceUnavaliable"
            security:
                - bearerAuth: []
                  Agid-JWS-Signature: []

components:
    responses:
        OKRequest:
            description: Richiesta completata con successo
            headers:
                Agid-JWS-Signature:
                    $ref: "#/components/headers/Agid-JWS-Signature"

        BadRequest:
            description: Forma della richiesta non conforme alla specifica
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
            headers:
                Agid-JWS-Signature:
                    $ref: "#/components/headers/Agid-JWS-Signature"
        ServiceUnavaliable:
            description: Servizio non disponibile
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
            headers:
                Agid-JWS-Signature:
                    $ref: "#/components/headers/Agid-JWS-Signature"

        Unauthorized:
            description: Richiesta non autorizzata
            headers:
                Agid-JWS-Signature:
                    $ref: "#/components/headers/Agid-JWS-Signature"
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
        ServerError:
            description: Errore processamento richiesta
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
            headers:
                Agid-JWS-Signature:
                    $ref: "#/components/headers/Agid-JWS-Signature"

    schemas:
        Error:
            type: object
            description: codice e descrizione condizione di errore
            properties:
                code:
                    type: string
                message:
                    type: string
            required:
                - code
                - message
        SendInstanceRequest:
            type: object
            properties:
                cui:
                    $ref: https://raw.githubusercontent.com/AgID/suap-gt-specifiche/to_interoperabilita-protocols/to_interoperabilita/schema/cui-schema.yaml
                instance_index:
                    $ref: https://raw.githubusercontent.com/AgID/suap-gt-specifiche/to_interoperabilita-protocols/to_interoperabilita/schema/instance-index-schema.yaml

    headers:
        Agid-JWS-Signature:
            schema:
                format: JWS
                maxLength: 4096
                type: string
                example: eyJzd.fafa.fafafa
            description: |-
                Il valore di questo header è una token JWT firmato secondo la specifica JWS.
                Vedi Modi  [integrity_rest_01] Integrità del payload del messaggio REST.

    securitySchemes:
        bearerAuth:
            scheme: bearer
            bearerFormat: JWT
            type: http
            description: Implementazione conforme ad RFC8725

        Agid-JWS-Signature:
            type: apiKey
            description: |-
                Il valore di questo header è una token JWT firmato secondo la specifica JWS.
                Vedi Modi  [integrity_rest_01] Integrità del payload del messaggio REST.
            name: Agid-JWS-Signature
            in: header
