sequenceDiagram
    autonumber

    actor P as Presentatore    
    participant F as FrontOffice SUAP
    participant C as Catalogo SSU    
    participant B as BackOffice SUAP    
    actor O as Operatore SUAP    
    participant E as Enti Terzi    
 
    Note over F,B: istanza procedibile
    
	B ->> C: setting_time_CdSA(CUI)
    C -->> B: ack

    B ->> C: request_instance_descriptor(CUI)
    C -->> B: instanceDescriptor
    Note over C,B: ET endpoint may be changed
    
    par per ogni ente terzo interessato        
        B ->> E: send_instance(CUI)
        E -->> B: ack
        E ->> C: request_instance_descriptor(CUI)
        C -->> E: instanceDescriptor
        E ->> B: request_instance(CUI)
        B -->> E: instance
    end
    
        
    par almeno un ente terzo
        E ->> B: integration_request(CUI,integration_request_ente_terzo)
        B -->> E: ack            
    end

    Note over B: concluso il tempo di richiesta integrazione OR tutti gli enti terzi hanno richiesto integrazione
    B ->> F: integration_request(CUI,integration_request_all)
    F -->> B: ack
    B ->> C: audit(CUI,integration_request)
    C -->> B: ack
    F -) P: integration_request(CUI)
    B ->> C: audit(CUI,integration_request)
    C -->> B: ack

    alt entro i tempi di integrazione
        P --) F: instanceIntegrated
        F ->> B: send_instance(CUI)
        B -->> F: ack
        B ->> F: request_instance(CUI)
        F -->> B: instance
        par per ogni ente terzo interessato                
            B ->> E: send_istance(CUI)
            E -->> B: ack
            E ->> F: request_instance(CUI)
            F -->> E: instance
        end
        B ->> C: audit(CUI,request_instance_integrated)
        C -->> B: ack 

        par almeno un ente terzo
            E ->> B: send_conclusions(CUI,reasoned_suspension)
            B -->> E: ack            
        end

        Note over B: concluso il tempo dell'istanza o tutti gli enti terzi hanno inoltrato conclusione
        B ->> F: ending_instance(CUI,reasoned_suspension)
        F -->> B: ack            
        par per ogni ente terzo interessato
            B ->> E: ending_instance(CUI,reasoned_suspension)
            E -->> B: ack
        end
        B ->> C: audit(CUI,reasoned_suspension)
        C -->> B: ack
    else oltre i tempo di integrazione
        B ->> F: ending_instance(CUI,integration_times_ending)
        F -->> B: ack
        par per ogni ente terzo interessato
            B ->> E: ending_instance(CUI,integration_times_ending)
            E -->> B: ack
        end
        B ->> C: audit(CUI,integration_times_ending)
        C -->> B: ack
    end
       