sequenceDiagram
    autonumber
  
    participant F as FrontOffice SUAP
    participant C as Catalogo SSU    
    participant B as BackOffice SUAP    
    participant E as Enti Terzi    
 
    Note over F,B: istanza procedibile


            
    B ->> F: ending_instance(CUI,CdSS_convened)
    F -->> B: ack    

    par per ogni ente terzo interessato
        B ->> E: ending_instance(CUI,CdSS_convened)
        E -->> B: ack
    end
    
    B ->> C: audit(CUI,CdSS_convened)
    C -->> B: ack
        
   