sequenceDiagram
    autonumber

    actor P as Presentatore    
    participant F as FrontOffice SUAP
    participant C as Catalogo SSU    
    participant B as BackOffice SUAP    
    actor O as Operatore SUAP    
    participant E as Enti Terzi    
 
    Note over F,B: istanza procedibile

    
    par per ogni ente terzo interessato        
        B ->> E: send_instance(CUI)
        E -->> B: ack
        B ->> C: audit(CUI,instance_to_ET_sended)
        C -->> B: ack
        E ->> C: request_instance_descriptor(CUI)
        C -->> E: instanceDescriptor
        E ->> B: request_instance(CUI)
        B -->> E: instance
        E ->> C: audit(CUI,instance_retrived)
        C -->> E: ack
    end

    Note over B: concluso il tempo per richiesta integrazione
    par per ogni ente terzo interessato 
        B ->> E: ending_integration(CUI)
        E -->> B: ack
    end
        B ->> C: audit(CUI,ending_integration)
        C -->> B: ack

    par almeno un ente terzo
        E ->> B: send_conclusions(CUI,reasoned_suspension)
        B -->> E: ack 
        E ->> C: audit(CUI,reasoned_suspension)
        C -->> E: ack           
    end

    Note over B: concluso il tempo dell'istanza o tutti gli enti terzi hanno inoltrato conclusione
    B ->> F: ending_instance(CUI,reasoned_suspension)
    F -->> B: ack            
    par per ogni ente terzo interessato
        B ->> E: ending_instance(CUI,reasoned_suspension)
        E -->> B: ack
    end
    B ->> C: audit(CUI,reasoned_suspension)
    C -->> B: ack

    F -) P: notification(CUI,reasoned_suspension)

      