sequenceDiagram
    autonumber
       
    participant F as FrontOffice SUAP
    participant C as Catalogo SSU    
    participant B as BackOffice SUAP    
    actor O as Operatore SUAP    
    participant E as Enti Terzi    
   
    Note over F,B: istanza procedibile

    B ->> C: setting_time_CdSA(CUI)
    C -->> B: ack
     
    B ->> C: request_instance_descriptor(CUI)
    C -->> B: instanceDescriptor
    Note over C,B: ET endpoint may be changed
    
    par per ogni ente terzo interessato        
        B ->> E: send_instance(CUI)
        E -->> B: ack
        B ->> C: audit(CUI,instance_to_ET_sended)
        C -->> B: ack
        E ->> C: request_instance_descriptor(CUI)
        C -->> E: instanceDescriptor
        E ->> B: request_instance(CUI)
        B -->> E: instance
        E ->> C: audit(CUI,instance_retrived)
        C -->> E: ack
    end
        
    par almeno un ente terzo
        E ->> B: integration_request(CUI,CdSS_convocation)
        B -->> E: ack   
        E ->> C: audit(CUI,integration_requested)
        C -->> E: ack    		
    end

    
    Note over B: concluso il tempo di richiesta integrazione OR tutti gli enti terzi hanno richiesto integrazione
    B ->> C: audit(CUI,ending_integration)
    C -->> B: ack
 
    B ->> F: ending_instance(CUI,CdSS_convocation)
    F -->> B: ack            
    par per ogni ente terzo interessato
        B ->> E: ending_instance(CUI,CdSS_convocation)
        E -->> B: ack
    end
    B ->> C: audit(CUI,CdSS_convocation)
    C -->> B: ack
        