sequenceDiagram
    autonumber
    
    participant CU as ComUnica
    actor P as Presentatore    
    participant F as FrontOffice SUAP
    participant C as Catalogo SSU    
    participant B as BackOffice SUAP    
    actor O as Operatore SUAP    
   
    note over P,C: procedimenti individuati
    note over F,C: Metadati procedimenti recuperati
    note over P,F: Istanza complilata e firmata

    F ->> C: request_CUI(instanceDescriptor)
    C -->> F: instanceDescriptor

    F ->> B: send_instance(CUI)
    B -->> F: ack
    alt via ComUnica
        F -->> CU: ack
        CU -->> P: receipt
    else not via ComUnica
        F -->> P: receipt
    end
    B ->> C: request_instance_descriptor(CUI)
    C -->> B: instanceDescriptor
    B ->> F: request_instance(CUI)
    F -->> B: instance

    O -) B: request_instance(CUI)
    B -->> O: instance
    Note over B,O: entro tempo controllo formale
    
    opt
        O -) B: formalControlOK OR formalControlKO
        alt formal control KO
            B ->> F: formalControlKO
            F -) P: request_correction(CUI)
            B ->> C: audit(CUI,request_correction)
            C -->> B: ack
            P --) F: instanceCorrect
            F ->> B: send_instance(CUI)
            B -->> F: ack
            B ->> F: request_instance(CUI)
            F -->> B: instance
            B ->> C: audit(CUI,request_instance_correct)
            C -->> B: ack            
        end
    end

    B -) O: check_admissibility(CUI)
    O --) B: admissibilityOK OR admissibilityKO
    
    alt admissibility KO
        B ->> F: instance_refused(CUI)
        F -->> B: ack
        F -) P: instanceRefused            
        B ->> C: audit(CUI,instance_refused)
        C -->> B: ack                        
    else admissibility OK
        
        Note over B,F: istanza procedibile
       
end