sequenceDiagram
    autonumber
    
    participant CU as ComUnica
    actor P as Presentatore    
    participant F as FrontOffice SUAP
    participant C as Catalogo SSU    
    participant B as BackOffice SUAP    
    actor O as Operatore SUAP    
   
    note over P,C: procedimenti individuati
    note over F,C: Metadati procedimenti recuperati
    note over P,F: Istanza complilata e firmata

    F ->> C: request_CUI(instanceDescriptor)
    C -->> F: instanceDescriptor

    F ->> B: send_instance(CUI)
    B -->> F: ack
    F ->> C: audit(CUI,instance_to_BO_sended)
    C -->> F: ack

    alt via ComUnica
	    F ->> CU: send_instance(CUI)
		CU -->> F: ack
		CU ->> C: request_instance_descriptor(CUI)
		C -->> CU: instanceDescriptor
		
        loop per ogni procedimento parte dell'istanza
        CU ->> F:  request_instance_part(CUI, code_proc)
        F -->> CU:: instancePart
        end
        
        CU -) P: receipt
        CU ->> F: notify_receipt_sended(CUI)
        F -->> CU: ack
    else not via ComUnica
        F -) P: receipt
    end

    F ->> C: audit(CUI,receipt_sended)
    C -->> F: ack

    
    B ->> C: request_instance_descriptor(CUI)
    C -->> B: instanceDescriptor
    loop per ogni procedimento parte dell'istanza 
    B ->> F: request_instance_part(CUI, code_proc)
    F -->> B: instancePart
    end
    B ->> C: audit(CUI,instance_retrived)
    C -->> B: ack
    

    O -) B: lookup_instance(CUI)
    B -->> O: instance
        
    opt entro tempo controllo formale
        O -) B: formalControlOK OR formalControlKO
        alt formal control KO
            B ->> F: request_correction(CUI,correction_list)
            F -->> B: ack
            F -) P: request_correction(CUI,correction_list)
            B ->> C: audit(CUI,correction_requested)
            C -->> B: ack
            P --) F: instanceCorrect
            F ->> B: send_instance(CUI)
            B -->> F: ack
            F ->> C: audit(CUI,corrected_instance_to_BO_sended)
            C -->> F: ack
            loop per ogni procedimento parte dell'istanza 
            B ->> F: request_instance_part(CUI, code_proc)
            F -->> B: instancePart
            end
            B ->> C: audit(CUI,corrected_instance_retrived)
            C -->> B: ack           
        end
    end

    O -) B: lookup_instance(CUI)
    B -->> O: instance
    O -) B: admissibilityOK OR admissibilityKO
    
    alt admissibility KO
        B ->> F: instance_refused(CUI)
        F -->> B: ack
        F -) P: instanceRefused            
        B ->> C: audit(CUI,instance_refused)
        C -->> B: ack                        
    else admissibility OK
        
        Note over B,F: istanza procedibile
       
end